server:
  port: 8095

spring:
  application:
    name: order-service-app
  temporal:
    namespace: default
    connection:
      target: 127.0.0.1:7233
    workersAutoDiscovery:
      packages: ru.amalyugin.orderservice